# Generated by Django 5.2.7 on 2026-06-25 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_expense_company_expensecategory_company_and_more"),
        ("users", "0005_user_allowed_portals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="income_type",
        ),
        migrations.RenameModel(
            old_name="IncomeType",
            new_name="IncomeCategory",
        ),
        migrations.CreateModel(
            name="IncomeSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="accounts.incomecategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="income",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incomes",
                to="accounts.incomesubcategory",
            ),
        ),
    ]
