# Generated by Django 6.0.3 on 2026-03-17 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Return"),
                            ("purchase", "Purchase Return"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Invoice number or Purchase order ID", max_length=100
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "return_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.TextField()),
                (
                    "processed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "returns",
                "ordering": ["-processed_at"],
            },
        ),
    ]
