# Generated by Django 5.2.7 on 2026-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
