# Generated by Django 5.2.7 on 2026-06-03 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_category_company_product_company_and_more"),
        ("users", "0005_user_allowed_portals"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=50)),
                ("start_number", models.IntegerField(default=1)),
                ("padding", models.IntegerField(default=3)),
                ("current_number", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.company",
                    ),
                ),
            ],
            options={
                "db_table": "product_prefixes",
                "ordering": ["-created_at"],
                "unique_together": {("company", "prefix")},
            },
        ),
    ]
