# Generated by Django 5.2.7 on 2026-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_invoicetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicetemplate",
            name="template_type",
            field=models.CharField(
                choices=[("tax", "Tax Invoice"), ("nontax", "Non-Tax Invoice")],
                default="nontax",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="is_tax_invoice",
            field=models.BooleanField(default=False),
        ),
    ]
