# Generated by Django 5.2.7 on 2026-06-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_invoicetemplate_template_type_and_more"),
        ("users", "0005_user_allowed_portals"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="invoicetemplate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="invoice_number",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="salesinvoice",
            unique_together={("company", "invoice_number")},
        ),
    ]
