# Generated by Django 5.2.7 on 2026-06-25 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_creditlog_company_customer_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="invoice_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
