# Generated by Django 6.0.3 on 2026-03-17 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        max_length=10,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("purchase", "Purchase"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Invoice number or Purchase ID", max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("bank", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
