# Generated by Django 5.2.7 on 2026-06-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("purchase", "Purchase"),
                    ("credit", "Credit Settlement"),
                    ("supplier", "Supplier Payment"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
