# Generated by Django 5.2.7 on 2026-06-25 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_reference_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
