# Generated by Django 6.0.3 on 2026-05-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="category",
            field=models.CharField(
                choices=[
                    ("inventory", "Inventory"),
                    ("purchases", "Purchases"),
                    ("sales", "Sales"),
                    ("returns", "Returns"),
                    ("financial", "Financial"),
                    ("users", "Users"),
                    ("reports", "Reports"),
                    ("accounts", "Accounts"),
                ],
                default="inventory",
                max_length=20,
            ),
        ),
    ]
