# Generated by Django 6.0.3 on 2026-05-31 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_permission_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "gstin",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="GSTIN"
                    ),
                ),
                (
                    "pan",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="PAN"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=5)),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                (
                    "financial_year_start",
                    models.IntegerField(default=4, help_text="Month number (1-12)"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company-scoped role. NULL = global role.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this user belongs to. NULL for superadmins.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "company")},
        ),
    ]
