# Generated by Django 5.2.7 on 2026-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_company_alter_role_name_auditlog_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="gst_invoice_prefix",
            field=models.CharField(default="GST-", max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_start_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="company",
            name="non_gst_invoice_prefix",
            field=models.CharField(default="INV-", max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="reset_invoice_number_yearly",
            field=models.BooleanField(default=True),
        ),
    ]
