# Generated by Django 5.2.7 on 2026-06-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_company_gst_invoice_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_portals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of portal keys this admin can access. e.g. ["billing","accounts"]',
            ),
        ),
    ]
